//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Src\dark_repository\Evaluator\\Evaluator.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EvaluatorParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IEvaluatorListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EvaluatorParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] EvaluatorParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EvaluatorParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] EvaluatorParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentCommand([NotNull] EvaluatorParser.AssignmentCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentCommand([NotNull] EvaluatorParser.AssignmentCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionCommand([NotNull] EvaluatorParser.ExpressionCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionCommand([NotNull] EvaluatorParser.ExpressionCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BrackExpr</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBrackExpr([NotNull] EvaluatorParser.BrackExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BrackExpr</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBrackExpr([NotNull] EvaluatorParser.BrackExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulDiv([NotNull] EvaluatorParser.MulDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulDiv([NotNull] EvaluatorParser.MulDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddSub([NotNull] EvaluatorParser.AddSubContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddSub([NotNull] EvaluatorParser.AddSubContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableFactor([NotNull] EvaluatorParser.VariableFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableFactor([NotNull] EvaluatorParser.VariableFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberFactor([NotNull] EvaluatorParser.NumberFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberFactor([NotNull] EvaluatorParser.NumberFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EvaluatorParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] EvaluatorParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EvaluatorParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] EvaluatorParser.FactorContext context);
}
