//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Src\dark_repository\Evaluator\\Evaluator.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEvaluatorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class EvaluatorBaseListener : IEvaluatorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EvaluatorParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] EvaluatorParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EvaluatorParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] EvaluatorParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AssignmentCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentCommand([NotNull] EvaluatorParser.AssignmentCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AssignmentCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentCommand([NotNull] EvaluatorParser.AssignmentCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpressionCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionCommand([NotNull] EvaluatorParser.ExpressionCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpressionCommand</c>
	/// labeled alternative in <see cref="EvaluatorParser.cmd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionCommand([NotNull] EvaluatorParser.ExpressionCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BrackExpr</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBrackExpr([NotNull] EvaluatorParser.BrackExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BrackExpr</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBrackExpr([NotNull] EvaluatorParser.BrackExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulDiv([NotNull] EvaluatorParser.MulDivContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulDiv</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulDiv([NotNull] EvaluatorParser.MulDivContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddSub([NotNull] EvaluatorParser.AddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddSub([NotNull] EvaluatorParser.AddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableFactor([NotNull] EvaluatorParser.VariableFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableFactor([NotNull] EvaluatorParser.VariableFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberFactor([NotNull] EvaluatorParser.NumberFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberFactor</c>
	/// labeled alternative in <see cref="EvaluatorParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberFactor([NotNull] EvaluatorParser.NumberFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EvaluatorParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] EvaluatorParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EvaluatorParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] EvaluatorParser.FactorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
